# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']


#app.TodoController:
#class: AppBundle\Controller\TodoController
#tags:
 #  - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }